-- Foundation objects for the lab.
-- Run this first before any other SQL scripts.
CREATE DATABASE IF NOT EXISTS CLAIMS_POC;
USE DATABASE CLAIMS_POC;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CTRL;
CREATE SCHEMA IF NOT EXISTS INT;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS SEM;
CREATE SCHEMA IF NOT EXISTS SEMANTIC;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
