USE DATABASE CLAIMS_POC;
USE SCHEMA RAW;

-- Internal stage for snapshot files
CREATE OR REPLACE STAGE CLAIMS_NIGHTLY_STAGE;

-- CSV file format
CREATE OR REPLACE FILE FORMAT CSV_FF
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL');
