USE DATABASE CLAIMS_POC;

-- RAW layer
TRUNCATE TABLE IF EXISTS RAW.CLAIMS_SNAPSHOT_NIGHTLY;
TRUNCATE TABLE IF EXISTS RAW.CLAIMS_EVENTS_NIGHTLY;

-- INT layer
TRUNCATE TABLE IF EXISTS INT.CLAIMS_SNAPSHOT;
TRUNCATE TABLE IF EXISTS INT.CLAIMS_EVENTS;
TRUNCATE TABLE IF EXISTS INT.DIM_POLICY;
TRUNCATE TABLE IF EXISTS INT.DIM_CUSTOMER;
TRUNCATE TABLE IF EXISTS INT.DIM_ACTOR;

-- GOLD layer
TRUNCATE TABLE IF EXISTS GOLD.CLAIMS_MART;
